"""add_products

Revision ID: 14afef4afaab
Revises: 8cc5e93e1e14
Create Date: 2026-02-26 19:17:53.449217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '14afef4afaab'
down_revision: Union[str, Sequence[str], None] = '8cc5e93e1e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO product (id, name, created_at) VALUES (1, 'Default Product', CURRENT_TIMESTAMP)")
    # Advance the PostgreSQL sequence so auto-generated IDs don't collide with the
    # explicit id=1 we just inserted. Safe to ignore on SQLite (no sequences).
    conn = op.get_bind()
    if conn.dialect.name == "postgresql":
        conn.execute(sa.text("SELECT setval(pg_get_serial_sequence('product', 'id'), MAX(id)) FROM product"))
    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), server_default=sa.text('1'), nullable=True))
        batch_op.create_foreign_key('fk_interview_id', 'product', ['product_id'], ['id'])

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), server_default=sa.text('1'), nullable=True))
        batch_op.create_foreign_key('fk_opportunity_id', 'product', ['product_id'], ['id'])

    with op.batch_alter_table('outcome', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), server_default=sa.text('1'), nullable=True))
        batch_op.create_foreign_key('fk_outcome_id', 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcome', schema=None) as batch_op:
        batch_op.drop_constraint('fk_outcome_id', type_='foreignkey')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_constraint('fk_opportunity_id', type_='foreignkey')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.drop_constraint('fk_interview_id', type_='foreignkey')
        batch_op.drop_column('product_id')

    op.drop_table('product')
    # ### end Alembic commands ###
