"""fix_schema_drift

Revision ID: 65cba31159d2
Revises: e24fdb0a4886
Create Date: 2026-03-04 14:18:30.450025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cba31159d2'
down_revision: Union[str, Sequence[str], None] = 'e24fdb0a4886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviewfeedback', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('interviewfeedback_interview_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_interviewfeedback_interview_id'))
        batch_op.create_index(batch_op.f('ix_interviewfeedback_interview_id'), ['interview_id'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_username_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('user_username_key'), ['username'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('interviewfeedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviewfeedback_interview_id'))
        batch_op.create_index(batch_op.f('ix_interviewfeedback_interview_id'), ['interview_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('interviewfeedback_interview_id_key'), ['interview_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
