"""workspace-collaboration

Revision ID: 78b07d49fc61
Revises: n8o9p0q1r2s3
Create Date: 2026-03-07 13:46:04.797483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b07d49fc61'
down_revision: Union[str, Sequence[str], None] = 'n8o9p0q1r2s3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productmember', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_productmember_product_user'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productmember', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_productmember_product_user'), ['product_id', 'user_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
