"""add_theme_column

Revision ID: 8156ee0fb077
Revises: bfba4ba0fae5
Create Date: 2026-02-24 22:11:24.406467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8156ee0fb077'
down_revision: Union[str, Sequence[str], None] = 'bfba4ba0fae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'Uncategorized'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
