"""add_nested_opportunities

Revision ID: 8cc5e93e1e14
Revises: 6660c16a5a88
Create Date: 2026-02-26 08:54:44.265319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8cc5e93e1e14'
down_revision: Union[str, Sequence[str], None] = '6660c16a5a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_opp_parent', 'opportunity', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_constraint('fk_opp_parent', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
